"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['TimeCalc.py']
DATA_FILES = []
OPTIONS = {
    'packages': ['customtkinter', 'darkdetect', 'PIL'],
    'includes': ['Foundation', 'PyObjCTools'],
    'plist': {
        'LSMinimumSystemVersion': '15.0',
    },
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
)
